export const events = [
  {
    title: "Google I/O 2026",
    image: "/images/event1.png",
    slug: "google-io-2026",
    location: "Mountain View, CA",
    date: "May 19-20, 2026",
    time: "10:00 AM PT",
  },
  {
    title: "Microsoft Build 2026",
    image: "/images/event2.png",
    slug: "microsoft-build-2026",
    location: "San Francisco, CA",
    date: "June 2-3, 2026",
    time: "9:00 AM PT",
  },
  {
    title: "Apple WWDC26",
    image: "/images/event3.png",
    slug: "apple-wwdc26",
    location: "Online and Apple Park",
    date: "June 8-12, 2026",
    time: "10:00 AM PT",
  },
  {
    title: "GitHub Universe 2026",
    image: "/images/event4.png",
    slug: "github-universe-2026",
    location: "San Francisco, CA",
    date: "October 28-29, 2026",
    time: "9:00 AM PT",
  },
  {
    title: "KubeCon + CloudNativeCon North America 2026",
    image: "/images/event5.png",
    slug: "kubecon-cloudnativecon-na-2026",
    location: "Salt Lake City, UT",
    date: "November 9-12, 2026",
    time: "9:00 AM MT",
  },
  {
    title: "AWS re:Invent 2026",
    image: "/images/event6.png",
    slug: "aws-reinvent-2026",
    location: "Las Vegas, NV",
    date: "November 30-December 4, 2026",
    time: "8:00 AM PT",
  },
];
